### PR TITLE
Running on Docker

### PR DESCRIPTION
**Pull request by brunokrebs**

### CODE REVIEW

**Comment by brunokrebs** [comment]
Copied from this [GitHub repository](https://github.com/avatsaev/angular4-docker-example/).

**Comment by kmaida** [comment]
@brunokrebs were you still interested in Dockerizing, with all the newer changes we discussed?

**Comment by brunokrebs** [comment]
Not sure I see how one thing affect the other. But I submitted this a long time ago. Feel free to close it if you prefer.

**Comment by kmaida** [comment]
If you still need it, can you verify it still works with latest Angular version in this repo? We may want to put it in a Docker branch so as not to confuse users who are not containerizing. Closing for that reason, but we could make a branch in the future if you'd like.

**Pull request closed without merging**
